version: '3.8'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=db_forum
      - MYSQL_USER=carlo
      - MYSQL_ROOT_PASSWORD=Test12345.
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
